# -*- coding: utf-8 -*-
"""
Created on Sat Feb 17 23:00:52 2018

@author: SrivatsanPC
"""

DEFAULT_BINOMIAL_ACCURACY = 0.5

HASHTAG_PLACEHOLDER = 'HHHPLACEHOLDERHHH'

MENTION_PLACEHOLDER = 'MMMPLACEHOLDERMMM'