# -*- coding: utf-8 -*-
"""
Created on Sat Feb 17 23:00:52 2018

@author: SrivatsanPC
"""

RANDOM_STATE = 231

TEST_SET_SIZE = 0.2

DEFAULT_BINOMIAL_ACCURACY = 0.5

HASHTAG_PLACEHOLDER = 'HHHPLACEHOLDERHHH'
MENTION_PLACEHOLDER = 'MMMPLACEHOLDERMMM'

ONE_DATASET_ID = 14680

MIN_NGRAMS = 1
MAX_NGRAMS = 1

EMBEDDINGS_DIMENSION = 300
EMBEDDINGS_FILENAME = 'embeddings/embeddings_numpy_array.npy'
WORD_TO_IX_EMBEDDINGS_FILENAME = 'embeddings/word_to_index_dict.pkl'
UNKNOWN_KEY = '<UNKNOWN>'