# -*- coding: utf-8 -*-

TRAINING_FILES_LOCATION = 'data/'

RANDOM_STATE = 231

TEST_SET_SIZE = 0.2

DEFAULT_BINOMIAL_ACCURACY = 0.5

HASHTAG_PLACEHOLDER = 'HHHPLACEHOLDERHHH'
MENTION_PLACEHOLDER = 'MMMPLACEHOLDERMMM'

ONE_DATASET_ID = 14680

MIN_NGRAMS = 1
MAX_NGRAMS = 1