# -*- coding: utf-8 -*-

PATH_TO_LABELED_DATA = "../data/classification/labeled_datasets/"
PATH_TO_TRAINED_EMBEDDINGS = "../data/embeddings/trained_embeddings/"

RANDOM_STATE = 231

TEST_SET_SIZE = 0.2

DEFAULT_BINOMIAL_ACCURACY = 0.5

HASHTAG_PLACEHOLDER = 'HHHPLACEHOLDERHHH'
MENTION_PLACEHOLDER = 'MMMPLACEHOLDERMMM'

ONE_DATASET_ID = 14680

MIN_NGRAMS = 1
MAX_NGRAMS = 2

EMBEDDINGS_DIMENSION = 300
EMBEDDINGS_FILENAME = 'embeddings_numpy_array.npy'
WORD_TO_IX_EMBEDDINGS_FILENAME = 'word_to_index_dict.pkl'
UNKNOWN_KEY = '<UNK>'

FIRST_BRAND_ID = 8009
LAST_BRAND_ID = 19150

